### ISSUE TITLE
python 2/3 future imports 

### ISSUE THREAD

**Issue by crotwell** [EarthScope/portable-fdsnws-dataselect#34]
I think the 2/3 compatibility imports are not correct:

```
portable-fdsnws-dataselect -s
Traceback (most recent call last):
  File "/home/scsn/.local/bin/portable-fdsnws-dataselect", line 5, in <module>
    from portable_fdsnws_dataselect.server import main
  File "/home/scsn/.local/lib/python3.10/site-packages/portable_fdsnws_dataselect/server.py", line 22, in <module>
    from portable_fdsnws_dataselect.handler import HTTPServer_RequestHandler
  File "/home/scsn/.local/lib/python3.10/site-packages/portable_fdsnws_dataselect/handler.py", line 7, in <module>
    from future.standard_library import install_aliases
ModuleNotFoundError: No module named 'future'
```

As python2 is EOL, maybe easiest to just drop python2 support.

**Comment by chad-earthscope** [comment]
> As python2 is EOL, maybe easiest to just drop python2 support.

This.  Not only is dropping support for 2 in future releases justified, it will simplify the development aspects significantly.
